server:
  port: 9494
spring:
  application:
    name: GLOBALCONFIGS

  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO:https://github.com/davidwillianx/superquiz}
          searchPaths: ${GIT_PATH:configserver/src/main/resourses/configs/**}
          clone-on-start: true



