server:
  port: 9494
spring:
  application:
    name: globalconfigs
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO:https://github.com/davidwillianx/superquiz-configs}
          search-paths:
            - '{application}/{profile}'
            - qauth
            - discovery
            - gateway
          clone-on-start: true
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVRY_PATH:http://localhost:9191/eureka}
