server:
  port: 9494
spring:
  application:
    name: GLOBALCONFIGS
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO:https://github.com/davidwillianx/superquiz-configs}
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_API:http://localhost:9191/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost
